### ISSUE TITLE
Front-End Wrap Up List- Phase I

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#346]
**Text Updates**
- [x] Text Update (https://github.com/enove/Thriver/issues/320)
- [x] Text Update (https://github.com/enove/Thriver/issues/319)

**Work**
- [x] Dynamic Sizing for Work LI (https://github.com/enove/Thriver/issues/344)
- [x] Streamline Columns in Evaluation (https://github.com/enove/Thriver/issues/318)

**Events/Calendar**
- [ ] Events Mobile (https://github.com/enove/Thriver/issues/250)
- [ ] Events Section should grow height w/ larger content
- [ ] Events section markdown is returning weird content / check other sections
- [ ] State vs National Events (https://github.com/enove/Thriver/issues/107)

 **Providers/Maps** 
- [ ] Enhanced Provider UI (https://github.com/enove/Thriver/issues/327)
- [ ] Pin Recolor for less important (https://github.com/enove/Thriver/issues/339)
- [ ] Map buttons - mobile
- [ ] Map should show county written out and not on click
- [ ] Map on county click zoom in and select 1 county if applicable.
- [ ] Maps: Empty Info Window on Load (https://github.com/enove/Thriver/issues/152)
- [ ] On county click expand to location.
- [ ] Could some counties on click populate a provider while some not?
- [ ] ALWAYS show whole state
- [ ] Shade counties if possible.
- [ ] Add search bar on providers section.
- [ ] Download PDF of map and provider list.
- [ ] Sort alphabetically by county/name

 **Single Branches** 
- [ ] Add Full Featured Library back (https://github.com/enove/Thriver/issues/325)
- [ ] Quality Assurance (https://github.com/enove/Thriver/issues/110)
- [ ] Donation Fixes: (https://github.com/enove/Thriver/issues/242)
